name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      FLYCTL_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Make deploy script executable
        run: chmod +x ./ship-it.sh

      - name: Deploy (build + tests inside script)
        run: ./ship-it.sh
